### ISSUE TITLE
Local proxy address works on server and wifi devices, but not on LAN 

### ISSUE THREAD

**Issue by akhdanfadh** [zilexa/Homeserver#20]
### Problem
I find a similar discussion [here ](https://caddy.community/t/local-proxy-address-works-on-all-devices-except-host/15921) on Caddy community from you. But, instead of server in that case, I cannot access all local domain addresses (e.g. `http://plex.o/`) in my LAN-connected devices (e.g. local PC, chromecast). I can access them on wifi devices though, like my phone and laptop.

Another note, I can still access the services using `serverip:port` but not via `*.o/`.

### Environment
- Clean install using this repo
- Set *.o to my server IP using AdGuard Home -> works great
- Set my server IP to be static in the router, though I am not sure it is necessary (not mention anywhere in this guide)
- Router DNS setting see below

### Confusion
There are two 'Primary DNS' setting that I can change in my router (TP-Link Archer C1200): one in the internet IPv4 setting where right now it is set to automatically configured by ISP, and the other in the DHCP setting where I can just put my server ip there (it was initially blank). When I work around with these two settings, I found that the one in DHCP is the main setup that allow my wifi devices to access those local domain addresses.

**Comment by akhdanfadh** [comment]
I ended up solving the DNS setting for both IPv4 and IPv6 in my local devices, not the router. I guess I need to understand more on the networking part.

Btw, thank you for this homeserver repo! I learnt a lot and may later try to create another dumb server on virtual box.

**Comment by zilexa** [comment]
Feel free to reopen when needed.
