### ISSUE TITLE
docker/readme.md is outdated

### ISSUE THREAD

**Issue by shionryuu** [zilexa/Homeserver#22]
> Go to http://go.o/, this is your server start page! Go to Settings > Docker > Enable API, leave settings and notice all your apps are there, configure your Bookmarks at will.

[docker/README.md](https://github.com/zilexa/Homeserver/blob/master/docker/README.md) is outdated, flame start page was removed

**Comment by zilexa** [comment]
Thanks! I changed the sentence. Also added a suggestion for Dashy in case people want more than the simple Plugsy dashboard.
