### ISSUE TITLE
Error when creating datapools (and maybe mount points)

### ISSUE THREAD

**Issue by SimpleMachine247** [zilexa/Homeserver#23]
Up until Step 2b. (Create Your Datapools) I have had minimal issues with the instructions and scripts working out as expected. I am going with 'Option 1' for my storage.

In 2a, I wiped drives /dev/sda, /dev/sdc, and /dev/sdd and created individual file systems as follows:
```
mkfs.btrfs -m dup -L data1 /dev/sda
mkfs.btrfs -m dup -L data0 /dev/sdc
mkfs.btrfs -m dup -L backup0 /dev/sdd
```

All were successful, although I did have an issue where I needed to use sudo for the commands to work (which is not listed in the instructions)

I created the mountpoints as instructed
`sudo mkdir -p /mnt/disks/{data0,data1,backup0}`

Made sure each was unmounted (They do not seem to ever have been mounted up the this point, so there is a 'not mounted' message) and modified my fstab as directed (attached fstab up to line 31). Running sudo mount -a returns no output as expected, but when I go to verify that the discs are mounted to the right paths with sudo lsblk or sudo mount -l the only drive showing mounted is my NVMe. data0,data1,backup0 are not mounted. I'm not actually sure if they are supposed to be at this point since from what I understand adding the noauto option in fstab would stop the drives from getting mounted with sudo mount -a.

At this point, except for the mounting thing, everything seems good to go. I check out Folder Structure Recommendations & Data Migration, but it seems like this bit should not be done until after 2b. since it references the subvolumes we are about to create. (Side note, the link to the create_folderstructure.sh script is broken)

Pool is created with sudo mkdir -p /mnt/pool/{users, media}, subvolumes are created as:
```
sudo btrfs subvolume create /mnt/disks/data0/Media
sudo btrfs subvolume create /mnt/disks/data1/Zach
```

Drive pools are added to fstab by adding lines 33 - 37 in the attached fstab file. I originally used the example lines on the exapmle fstab file instead of the lines on the 2b page, but the example file adds the subvol=Users option and this caused /mnt/pool/users to fail as well, so I switched to the lines on the 2b page instead.

When sudo mount -a is run, the following error occurs:

> mount: /mnt/pool/media: mount(2) system call failed: No such file or directory.
>        dmesg(1) may have more information after failed mount system call.

/mnt/pool/users seems to be mounting correctly but Media still will not.

I've also attached a number of outputs that I hope are useful / relevant.

Apologies if this is in bad form or format, I have not submitted one of these before.

[fstab.txt](https://github.com/zilexa/Homeserver/files/11184312/fstab.txt)
[lsblk.txt](https://github.com/zilexa/Homeserver/files/11184325/lsblk.txt)
[subvolume_list.txt](https://github.com/zilexa/Homeserver/files/11184326/subvolume_list.txt)

**Comment by zilexa** [comment]
I've been a bit busy, but I will try to get back to you tomorrow. 
Did you already test if you can mount the on-demand mounts?
For example `sudo mount /mnt/disks/data0`

**Comment by SimpleMachine247** [comment]
I actually figured this out last night. The example fstab has /mnt/**drives**/data0 instead of /mnt/**disks**/data0 (etc) and I just copied the example lines and filled in the UUIDs instead of actually checking that I had the paths correct.

**Comment by zilexa** [comment]
Aha! My mistake then. I will go through the guide and change everything to `drives`. 
I used `disks` in the past, moved slowly to SATA SSDs that's why I believe `drives` is better because it can be an HDD or a SSD. An SSD does not have disks.
