### ISSUE TITLE
Orphaned link

### ISSUE THREAD

**Issue by rabelux** [zilexa/Homeserver#5]
I guess you moved some files as https://github.com/zilexa/Homeserver/tree/master/network%20share%20(NFSv4.2) in the readme points to nowhere.

**Comment by zilexa** [comment]
I have changed the structure completely and it's much more logical now. All steps are on the homepage. 

NFS is now within the filesystem section:
https://github.com/zilexa/Homeserver/tree/master/filesystem/networkshares_HowTo-NFSv4.2
