### ISSUE TITLE
www-custom.ini

### ISSUE THREAD

**Issue by QEDeD** [zilexa/Homeserver#6]
You mention the file www-custom.ini, in https://github.com/zilexa/Homeserver/blob/976191966016a4b5cdcb3ee027c9b5e29b35289d/docker/Extras/nextcloud.yml#L63, but as far as I can tell, the content of this file is not shown anywhere. 

Would you mind sharing the file or pointing me in the right direction in case I've missed it? Thanks :)

**Comment by arvigeus** [comment]
I believe the content is

```
pm.max_children = 15
pm.max_requests = 500
```

These are arbitrary numbers. Also I haven't tested it yet.

**Comment by zilexa** [comment]
I think you should just remove the line. The script it was based on used it for custom settings. I left it in case anyone would find it useful.

**Comment by zilexa** [comment]
I have commented that line out:
https://github.com/zilexa/Homeserver/blob/ba83a8a14aa1bfafd74ba9b90d9c125595582fd9/docker/Extras/nextcloud.yml#L65
