### ISSUE TITLE
question nextcloud

### ISSUE THREAD

**Issue by gregpalaci** [zilexa/Homeserver#7]
Sorry to ask, I see you don't use anymore, I think I'm almost up and going, I want to test locally without a domain just localhost and tried setting these,

I'm fairly familar with Caddy 1, somewhat with 2, ok with nextcloud setup also, ok with one docker file, but little lost with docker networking at the moment.

I think I had to setup a Swarm instance for this also, which seems solved on my end.

`labels:
  caddy.auto_https: "off"`

![Screenshot from 2021-12-06 18-45-55](https://user-images.githubusercontent.com/1177690/144940638-ef1f379c-58f9-4105-8e91-4ca736732e64.png)

I understand if you aren't supporting this file anymore, you can just close if you dont have time. cheers

**Comment by zilexa** [comment]
I have no clue what your issue is, the picture you added seems part of a screenshot. 

If the issue is with docker network isolation, try with

```
network_mode: host
```
Instead of `networks:`

This way you are not using docker network. The container is accessible via localhost or 127.0.0.1 or your host system IP address.

**Comment by gregpalaci** [comment]
Sorry to be specific, https isn't working locally, and http is auto forwarding to https regradless the ports I use.
Just trying to disable https auto redirect for local

**Comment by zilexa** [comment]
Know that all modern browsers will try https even when you typed http. It doesn't necessarily have to do with what you configure. Browsers really do their best not to load http and if there is no https it can lead to errors.
In Firefox, there is a little trick of adding a / at the end when you type your address: http://192.168.88.2:5000**/** that prevents Firefox from changing http to https.

Maybe that is the issue?

If it does have to do with your setup: you haven't shared anything I can look at.
But: 
When it comes to Caddy, I am really a noob. I recommend to ask either the creator of the Caddy Docker Proxy container: 
https://github.com/lucaslorentz/caddy-docker-proxy or the Caddy forum: caddy.community
Also I don't use Nextcloud myself so I can't test..

**Comment by gregpalaci** [comment]
thanks will investigate what you suggested

**Comment by ramolec** [comment]
I'm trying to do the same thing, run locally. But I'm trying this error when I try to connect.

`SSL_ERROR_INTERNAL_ERROR_ALERT`

I'm trying to get information on the reason, but I'm a little lost. Did you manage to run it locally @gregpalaci  could you share?

**Comment by gregpalaci** [comment]
@ramolec nope just went with another solution
